version: "3"

services:
  mongodb:
    image: mongo:4.0-xenial
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always

  mims-gateway:
    image: docker.nuarch.io/dsny/mims-gateway:v0.2.0-0-95cc001e7f
    ports:
      - 8080:8080
    links:
      - mims-reference-data
      - mims-reference-data-ui

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    restart: always

  mims-mongo-data-load:
    image: docker.nuarch.io/dsny/mims-mongo-data-load:v0.2.0-0-263cedc39b
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin
    entrypoint: bash -c "/wait-for-it.sh --timeout=0 mongodb:27017 && /entrypoint.sh"


  mims-reference-data:
    image: docker.nuarch.io/dsny/mims-reference-data-service:v0.3.0-0-8efb840634
    ports:
      - 8082:8080
    links:
      - mongodb
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_USERNAME: admin
      MONGO_PASSWORD: admin

  mims-reference-data-ui:
    image: docker.nuarch.io/dsny/mims-reference-data-ui-service:v0.3.0-0-43195d6e24
    ports:
      - 8083:8080
    depends_on:
      - mims-reference-data